/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.35.0
  Forc version: 0.35.3
  Fuel-Core version: 0.17.3
*/

export type { SwayStoreContractAbi } from './SwayStoreContractAbi';

export { SwayStoreContractAbi__factory } from './factories/SwayStoreContractAbi__factory';
