/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.59.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.5
*/

export type { ContractAbi } from './ContractAbi';

export { ContractAbi__factory } from './factories/ContractAbi__factory';
